### ISSUE TITLE
fragment callbacks

### ISSUE THREAD

**Issue by adityajangle** [CodeKul/android-5-6-daily#2]
which callbacks are necessary to be implemented in fragments

**Comment by aniruddhha** [comment]
`Usually, you should implement at least the following lifecycle methods:

onCreate()
The system calls this when creating the fragment. Within your implementation, you should initialize essential components of the fragment that you want to retain when the fragment is paused or stopped, then resumed.

onCreateView()
The system calls this when it's time for the fragment to draw its user interface for the first time. To draw a UI for your fragment, you must return a View from this method that is the root of your fragment's layout. You can return null if the fragment does not provide a UI.

onPause()
The system calls this method as the first indication that the user is leaving the fragment (though it doesn't always mean the fragment is being destroyed). This is usually where you should commit any changes that should be persisted beyond the current user session (because the user might not come back).`

[https://developer.android.com/guide/components/fragments](https://developer.android.com/guide/components/fragments)
